# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
runs-on: ubuntu-latest
  build:
  strategy:
    matrix:
      node-version: [16.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  steps:
    - uses: jirutka/setup-alpine@v1
      with:
        branch: v3.15

    - run: cat /etc/alpine-release
      shell: alpine.sh {0}

    - name: Use oxr463/setup-cordova
      uses: oxr463/setup-cordova@0.0.3
      with:
        exec: |
          cordova platform add android && \
          cordova build --no-telemetry && \
          cp "$(find . -name '*.apk')" .
